import type { SubjectSyllabus } from '@spikequiz/shared'

export const physics12: SubjectSyllabus = {
  subject: 'physics',
  class: 12,
  chapters: [
    {
      chapter_no: 1,
      chapter_name: 'Electric Charges and Fields',
      topics: [
        'Electric charge',
        'Conductors and insulators',
        'Coulombs law',
        'Electric field',
        'Electric dipole',
        'Electric flux',
        'Gauss theorem',
      ],
    },
    {
      chapter_no: 2,
      chapter_name: 'Electrostatic Potential and Capacitance',
      topics: [
        'Electric potential',
        'Potential difference',
        'Equipotential surfaces',
        'Capacitors',
        'Dielectrics',
        'Energy stored in capacitor',
      ],
    },
    {
      chapter_no: 3,
      chapter_name: 'Current Electricity',
      topics: [
        'Electric current',
        'Ohms law',
        'Resistance',
        'Resistivity',
        'Kirchhoffs laws',
        'Wheatstone bridge',
        'Meter bridge',
        'Potentiometer',
      ],
    },
    {
      chapter_no: 4,
      chapter_name: 'Moving Charges and Magnetism',
      topics: [
        'Magnetic field',
        'Biot-Savart law',
        'Amperes law',
        'Solenoid',
        'Toroid',
        'Force on moving charge',
        'Cyclotron',
      ],
    },
    {
      chapter_no: 5,
      chapter_name: 'Magnetism and Matter',
      topics: [
        'Bar magnet',
        'Magnetic field lines',
        'Earths magnetism',
        'Diamagnetism',
        'Paramagnetism',
        'Ferromagnetism',
        'Hysteresis',
      ],
    },
    {
      chapter_no: 6,
      chapter_name: 'Electromagnetic Induction',
      topics: [
        'Magnetic flux',
        'Faradays law',
        'Lenzs law',
        'Motional EMF',
        'Eddy currents',
        'Self inductance',
        'Mutual inductance',
      ],
    },
    {
      chapter_no: 7,
      chapter_name: 'Alternating Current',
      topics: [
        'AC voltage',
        'AC current',
        'Phasors',
        'LCR circuit',
        'Resonance',
        'Power in AC',
        'Transformer',
      ],
    },
    {
      chapter_no: 8,
      chapter_name: 'Electromagnetic Waves',
      topics: ['Displacement current', 'EM waves', 'EM spectrum', 'Properties of EM waves'],
    },
    {
      chapter_no: 9,
      chapter_name: 'Ray Optics and Optical Instruments',
      topics: [
        'Reflection',
        'Refraction',
        'Total internal reflection',
        'Lenses',
        'Prism',
        'Microscope',
        'Telescope',
      ],
    },
    {
      chapter_no: 10,
      chapter_name: 'Wave Optics',
      topics: [
        'Huygens principle',
        'Interference',
        'Youngs double slit',
        'Diffraction',
        'Polarization',
      ],
    },
    {
      chapter_no: 11,
      chapter_name: 'Dual Nature of Radiation and Matter',
      topics: [
        'Photoelectric effect',
        'Photon',
        'Einstein equation',
        'de Broglie wavelength',
        'Davisson-Germer experiment',
      ],
    },
    {
      chapter_no: 12,
      chapter_name: 'Atoms',
      topics: [
        'Alpha particle scattering',
        'Rutherford model',
        'Bohr model',
        'Hydrogen spectrum',
        'Energy levels',
      ],
    },
    {
      chapter_no: 13,
      chapter_name: 'Nuclei',
      topics: [
        'Nucleus composition',
        'Nuclear size',
        'Mass defect',
        'Binding energy',
        'Radioactivity',
        'Nuclear fission',
        'Nuclear fusion',
      ],
    },
    {
      chapter_no: 14,
      chapter_name: 'Semiconductor Electronics',
      topics: [
        'Semiconductors',
        'p-n junction',
        'Diode',
        'Zener diode',
        'LED',
        'Solar cell',
        'Transistor',
        'Logic gates',
      ],
    },
  ],
}
